# This file was generated by GoReleaser. DO NOT EDIT.
cask "treewright" do
  binary "treewright", target: "tw"

  caveats do
    replacing = cask.installed_version
    if replacing.nil? || replacing.to_s == "0.4.0"
      <<~FIRST_INSTALL
        Add the shell integration to your shell's startup file:
          eval "$(treewright shell-init zsh)"     # or bash
          treewright shell-init fish | source

        Then register a repository by running "tw setup" inside it.
        (tw is the installed short name; every command answers to it.)
      FIRST_INSTALL
    else
      <<~AFTER_UPGRADE
        The new binary is in place. Nothing that loaded the old one knows yet,
        so from a repository you use treewright in:

          tw refresh

        That rewrites every copy of the agent plugin — the user-level one, and
        any a worktree was given when it was created, which nothing has looked
        at since — and reloads the tmux key bindings into the server you are
        attached to.

        Open a new terminal as well: only a shell can replace its own
        functions, so this one keeps the old wrapper until it restarts.
        "tw doctor" says whether anything is still behind.
      AFTER_UPGRADE
    end
  end

  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "baa3146d230da6943e05aae8fcba201292c4c1e0efa24738049ce575e5fc6f34"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5141719acadd388f321377d12c45817a4187f88299b0b60ad89b795a10cafa46"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d3342b7066b711a99cc995f83b46a15bc2ce303c8df0ce2ca6660f6b7deeeef4"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "17f5edf65c480c0c2e8281a99ec32439ffe7983ebbb92e134f9dad1fed53e6c2"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_linux_amd64.tar.gz"
    end
  end

  name "treewright"
  desc "Give every ticket its own git worktree, tmux window, and agent session"
  homepage "https://github.com/jay-snyder/treewright"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "treewright"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/treewright"]
    end
  end

  # No zap stanza required
end
