# This file was generated by GoReleaser. DO NOT EDIT.
cask "treewright" do
  binary "treewright", target: "tw"

  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "11d76f8b598db9137050de58bc3ab4a5447823edb685c1acf30f3cea3c0f2c4c"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1837d532332c16432c6526ce010e2fac12f4b4f585dd1162b55543bf4477092"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3bdb8b8555759ea8036df47f255f63c3fc68670d7c72796d9a947f1f21191ec"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31b2d70f4654b984ea7fc150bb2ae9b8e7a05355dae10f05db520354e71a9955"
      url "https://github.com/jay-snyder/treewright/releases/download/v#{version}/treewright_#{version}_linux_arm64.tar.gz"
    end
  end

  name "treewright"
  desc "Give every ticket its own git worktree, tmux window, and agent session"
  homepage "https://github.com/jay-snyder/treewright"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "treewright"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/treewright"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Add the shell integration to your shell's startup file:
      eval "$(treewright shell-init zsh)"     # or bash
      treewright shell-init fish | source

    Then register a repository by running "tw setup" inside it.
    (tw is the installed short name; every command answers to it.)
  EOS
end
